[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-builder"
version = "1.0.0"
description = "A Streamlit-based ML model development guide promoting responsible AI"
authors = [{name = "Richard Wheeler"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
keywords = ["machine-learning", "streamlit", "responsible-ai", "model-development"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "streamlit>=1.24.0",
    "pandas>=1.5.0",
    "numpy>=1.23.0",
    "scikit-learn>=1.0.2",
    "plotly>=5.13.0,<7.0.0",
    "kaleido>=0.2.1",
    "networkx>=3.1",
    "category_encoders>=2.6.0",
    "shap>=0.41.0",
    "matplotlib>=3.6.0",
    "seaborn>=0.12.0",
    "scipy>=1.9.0",
    "dython>=0.7.3",
    "imblearn",
    "optbinning>=0.20.0",
    "streamlit-scroll-to-top",
    "fairlearn>=0.7.0",
    "Boruta>=0.3",
    "xgboost>=2.1.4",
    "lightgbm>=4.6.0",
    "python-magic>=0.4.27",
    "optuna>=3.5.0",
    "cmaes>=0.11.0",
    "lime>=0.2.0",
    "reportlab>=4.0.0",
    "catboost>=1.2.0",
]

[project.urls]
Homepage = "https://github.com/richardwheeler/ML_Builder_Beta"
Issues = "https://github.com/richardwheeler/ML_Builder_Beta/issues"

[project.scripts]
ml-builder = "ml_builder.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ml_builder*"]

[tool.setuptools.package-data]
ml_builder = [
    "*.md", 
    "*.txt", 
    "sample_data/*.csv",
    ".streamlit/*.toml"
]